"""
CIT200 HID Protocol Driver

Pure Python reimplementation of the Linksys CIT200 DECT phone HID protocol.
Reverse-engineered from eni_fp.dll, cit200.exe, and cit200xSkype.py.

USB Device: VID 0x13B1, PID 0x001D — Composite (Audio IF0 + HID Telephony IF3)
"""

import hid
import time
import struct
import logging
import threading
import platform
import ctypes
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Callable, Optional

log = logging.getLogger(__name__)

# USB identifiers
VID = 0x13B1
PID = 0x001D
INTERFACE = 3

# Online status values (index matches protocol byte)
class Status(IntEnum):
    ONLINE = 0
    OFFLINE = 1
    NA = 2
    AWAY = 3
    INVISIBLE = 4
    DND = 5
    SKYPEME = 6  # Maps to "available" in modern platforms


@dataclass
class Contact:
    """A contact entry to display on the handset."""
    index: int = 0
    handle: str = ""      # username / identifier
    name: str = ""        # display name
    status: int = 0       # Status enum value


class Event:
    """Events generated by handset button presses."""
    PING = "ping"
    CALL_BUTTON = "call_button"           # Green call button pressed
    END_CALL = "end_call"                 # Red end button pressed
    CONTACTS_REQUEST = "contacts_request" # Skype/contacts menu opened
    CONTACT_DETAILS = "contact_details"   # Contact detail view opened
    STATUS_MENU = "status_menu"           # Status menu selected
    STATUS_CHANGE = "status_change"       # User picked a new status
    DIAL = "dial"                         # Dialing a contact (callee data)
    ANSWER_INCOMING = "answer_incoming"   # Handset picked up incoming call
    REJECT_INCOMING = "reject_incoming"   # Handset rejected incoming call
    HOLD_RESUME = "hold_resume"           # R button pressed (hold/resume)
    VOICEMAIL_VIEW = "voicemail_view"
    VOICEMAIL_DELETE = "voicemail_delete"
    CALL_ACCEPTED_REMOTE = "call_accepted_remote"  # Outgoing call accepted by remote


class CIT200Device:
    """
    HID driver for the Linksys CIT200 USB base station.

    Communicates via 9-byte HID feature reports:
        byte 0: 0x04 (report ID)
        bytes 1-7: payload (7 bytes)
        byte 8: 0x68 (terminator)

    Reads 8-byte interrupt reports from the device.
    """

    def __init__(
        self,
        transport_mode: str = "dual",
        call_setup_delay: float = 0.2,
        call_connect_delay: float = 0.2,
        trace_path: Optional[str] = None,
        trace_window_s: float = 3.0,
        contacts_frame_delay_s: float = 0.001,
        contacts_contact_delay_s: float = 0.004,
        contacts_transport_mode: str = "feature_only",
    ):
        self._dev: Optional[hid.device] = None
        self._win_feature_handle = None
        self._win_feature_path = None
        self._running = False

        # Internal state machine (mirrors qwerty in reference)
        self._state = 0
        self._callee_buf = bytearray()
        self._contacts: list[Contact] = []
        self._current_status = Status.ONLINE

        # Callbacks
        self._callbacks: dict[str, list[Callable]] = {}
        self._msg_count = 0

        # Transport and timing knobs
        self._transport_mode = "dual"
        self.set_transport_mode(transport_mode)
        self._call_setup_delay = max(0.0, float(call_setup_delay))
        self._call_connect_delay = max(0.0, float(call_connect_delay))
        self._contacts_frame_delay_s = max(0.0, float(contacts_frame_delay_s))
        self._contacts_contact_delay_s = max(0.0, float(contacts_contact_delay_s))
        self._contacts_transport_mode = (contacts_transport_mode or "").strip().lower()
        if self._contacts_transport_mode not in {"", "feature_only", "output_only", "dual"}:
            self._contacts_transport_mode = "feature_only"

        self._io_lock = threading.Lock()
        self._read_error_streak = 0
        self._last_recover_attempt = 0.0

        # Guard overlapping call-setup sequences
        self._call_setup_lock = threading.Lock()
        self._call_setup_active = False

        # Optional fake time override — (hour, minute) tuple or None
        self._time_override: Optional[tuple] = None

        # Optional HID trace capture
        self._trace_path = trace_path
        self._trace_window_s = max(0.0, float(trace_window_s))
        self._trace_until = 0.0
        self._trace_t0 = time.perf_counter()
        self._trace_lock = threading.Lock()
        if self._trace_path:
            try:
                with open(self._trace_path, "w", encoding="ascii") as f:
                    f.write("# CIT200 HID trace\n")
            except OSError as e:
                log.error("Failed to open trace file %s: %s", self._trace_path, e)
                self._trace_path = None

    def set_transport_mode(self, mode: str):
        mode = (mode or "dual").strip().lower()
        alias = {
            "feature": "feature_only",
            "output": "output_only",
            "dual": "dual",
        }
        mode = alias.get(mode, mode)
        if mode not in {"feature_only", "output_only", "dual"}:
            raise ValueError(f"invalid transport mode: {mode}")
        self._transport_mode = mode
        log.debug("transport_mode set to %s", self._transport_mode)

    def _set_state(self, new_state: int, reason: str = ""):
        if new_state != self._state:
            log.debug("STATE %d -> %d %s", self._state, new_state, reason)
            self._trace_frame("EV", f"state {self._state}->{new_state} {reason}".strip())
        self._state = new_state

    def arm_trace_window(self, seconds: Optional[float] = None, reason: str = ""):
        if not self._trace_path:
            return
        window = self._trace_window_s if seconds is None else max(0.0, float(seconds))
        self._trace_until = max(self._trace_until, time.perf_counter() + window)
        log.debug("trace window %.3fs reason=%s", window, reason)
        self._trace_frame("EV", f"trace_window {window:.3f}s {reason}".strip())

    def _trace_frame(self, direction: str, payload):
        if not self._trace_path:
            return
        now = time.perf_counter()
        if direction in {"TX", "RX"} and now > self._trace_until:
            return

        if isinstance(payload, (bytes, bytearray)):
            line = " ".join(f"{b:02x}" for b in payload)
        else:
            line = str(payload)

        with self._trace_lock:
            try:
                with open(self._trace_path, "a", encoding="ascii") as f:
                    f.write(f"{now - self._trace_t0:9.3f} {direction} {line}\n")
            except OSError:
                pass

    def _timeline(self, label: str):
        """Emit compact call-state timeline markers to debug + trace."""
        log.debug("TIMELINE: %s", label)
        self._trace_frame("EV", f"timeline {label}")

    # ── Connection ──────────────────────────────────────────────

    def open(self) -> bool:
        """Open the HID device. Returns True on success."""
        self._dev = None
        self._win_feature_handle = None
        self._win_feature_path = None

        # Prefer explicit path open (more reliable on macOS when multiple
        # interfaces are exposed for the same VID/PID).
        try:
            entries = hid.enumerate(VID, PID) or []
        except Exception as e:
            entries = []
            log.debug("hid.enumerate failed: %s", e)

        if entries:
            def _score(entry: dict) -> int:
                score = 0
                iface = int(entry.get("interface_number", -1) or -1)
                usage_page = int(entry.get("usage_page", 0) or 0)
                usage = int(entry.get("usage", 0) or 0)
                if iface == INTERFACE:
                    score += 100
                if usage_page == 0x0B:  # Telephony usage page
                    score += 20
                if usage in {0x01, 0x05}:
                    score += 5
                return score

            candidates = sorted(entries, key=_score, reverse=True)
            for entry in candidates:
                path = entry.get("path")
                if not path:
                    continue

                dev = hid.device()
                tried = [path]
                if isinstance(path, str):
                    tried.append(path.encode("utf-8", "ignore"))

                opened = False
                for p in tried:
                    try:
                        dev.open_path(p)
                        opened = True
                        break
                    except OSError:
                        continue

                if not opened:
                    continue

                try:
                    dev.set_nonblocking(True)
                except Exception:
                    pass

                self._dev = dev
                if isinstance(path, (bytes, bytearray)):
                    try:
                        self._win_feature_path = path.decode("utf-8", errors="ignore")
                    except Exception:
                        self._win_feature_path = None
                elif isinstance(path, str):
                    self._win_feature_path = path

                if platform.system() == "Windows" and self._win_feature_path:
                    self._open_windows_feature_handle(self._win_feature_path)

                log.info(
                    "CIT200 opened via path (iface=%s usage_page=0x%02x usage=0x%02x)",
                    entry.get("interface_number", "?"),
                    int(entry.get("usage_page", 0) or 0),
                    int(entry.get("usage", 0) or 0),
                )
                return True

        # Fallback: generic VID/PID open.
        dev = hid.device()
        try:
            log.debug("opening HID device vid=%04x pid=%04x", VID, PID)
            dev.open(VID, PID)
            dev.set_nonblocking(True)
            self._dev = dev
            if platform.system() == "Windows":
                try:
                    entries = hid.enumerate(VID, PID) or []
                    for entry in entries:
                        iface = int(entry.get("interface_number", -1) or -1)
                        if iface != INTERFACE:
                            continue
                        p = entry.get("path")
                        if isinstance(p, (bytes, bytearray)):
                            self._win_feature_path = p.decode("utf-8", errors="ignore")
                        elif isinstance(p, str):
                            self._win_feature_path = p
                        break
                    if self._win_feature_path:
                        self._open_windows_feature_handle(self._win_feature_path)
                except Exception:
                    pass
            log.info("CIT200 opened: %s", self._dev.get_product_string())
            return True
        except OSError as e:
            log.error("Failed to open CIT200: %s", e)
            self._dev = None
            return False

    def close(self):
        """Disconnect and close the device."""
        if self._dev:
            log.debug("closing HID device")
            self._running = False
            # Send disconnect sequence
            self._write([0xc1, 0x33, 0x00, 0x43, 0x07, 0x9a, 0x4f])
            self._write([0x05, 0x0a, 0x01, 0x00, 0x00, 0x00, 0x00])
            time.sleep(0.2)
            self._dev.close()
            self._dev = None
            self._close_windows_feature_handle()
            log.info("CIT200 closed")

    def _open_windows_feature_handle(self, path: str):
        if platform.system() != "Windows":
            return
        if not path:
            return
        self._close_windows_feature_handle()
        try:
            kernel32 = ctypes.windll.kernel32
            GENERIC_READ = 0x80000000
            GENERIC_WRITE = 0x40000000
            FILE_SHARE_READ = 0x00000001
            FILE_SHARE_WRITE = 0x00000002
            OPEN_EXISTING = 3
            INVALID_HANDLE_VALUE = ctypes.c_void_p(-1).value

            handle = kernel32.CreateFileW(
                ctypes.c_wchar_p(path),
                GENERIC_READ | GENERIC_WRITE,
                FILE_SHARE_READ | FILE_SHARE_WRITE,
                None,
                OPEN_EXISTING,
                0,
                None,
            )

            if handle and handle != INVALID_HANDLE_VALUE:
                self._win_feature_handle = handle
                log.debug("Windows feature handle opened for interface path")
        except Exception as e:
            log.debug("Windows feature handle open failed: %s", e)

    def _close_windows_feature_handle(self):
        if platform.system() != "Windows":
            self._win_feature_handle = None
            return
        if not self._win_feature_handle:
            return
        try:
            ctypes.windll.kernel32.CloseHandle(self._win_feature_handle)
        except Exception:
            pass
        self._win_feature_handle = None

    def _set_feature_windows(self, buf: bytes) -> bool:
        if platform.system() != "Windows":
            return False
        if not self._win_feature_handle:
            return False
        try:
            hid_dll = ctypes.windll.hid
            arr = (ctypes.c_ubyte * len(buf)).from_buffer_copy(buf)
            ok = hid_dll.HidD_SetFeature(
                ctypes.c_void_p(self._win_feature_handle),
                ctypes.byref(arr),
                ctypes.c_ulong(len(buf)),
            )
            return bool(ok)
        except Exception:
            return False

    @property
    def is_open(self) -> bool:
        return self._dev is not None

    # ── Low-level I/O ───────────────────────────────────────────

    def _write(self, payload: list[int]):
        """
        Send a 7-byte payload as a 9-byte HID feature report.
        Format: [0x04] + payload(7) + [0x68]
        """
        if not self._dev:
            log.debug("skip write: device not open payload=%s", payload[:7])
            return
        raw_payload = payload[:7]
        safe_payload = [_clamp_byte(v) for v in raw_payload]
        if log.isEnabledFor(logging.DEBUG) and safe_payload != raw_payload:
            log.debug("write payload clamped: %s -> %s", raw_payload, safe_payload)

        buf = bytes([0x04] + safe_payload + [0x68])
        with self._io_lock:
            try:
                if not self._dev:
                    return

                sent_ok = False
                if self._transport_mode in {"feature_only", "dual"}:
                    try:
                        if platform.system() == "Windows":
                            t0 = time.perf_counter()
                            if self._set_feature_windows(buf):
                                sent_ok = True
                                log.debug("TX via feature report (HidD_SetFeature)")
                            dt_ms = (time.perf_counter() - t0) * 1000.0
                            if dt_ms > 200.0:
                                log.warning("HidD_SetFeature slow: %.1fms", dt_ms)
                        if not sent_ok:
                            ret = self._dev.send_feature_report(buf)
                            if ret and int(ret) > 0:
                                sent_ok = True
                                log.debug("TX via feature report")
                    except OSError:
                        pass

                if self._transport_mode in {"output_only", "dual"}:
                    try:
                        ret = self._dev.write(buf)
                        if ret is not None and int(ret) != 0:
                            sent_ok = True
                            log.debug("TX via output report")
                    except OSError:
                        pass

                if not sent_ok:
                    raise OSError("both feature and output report writes failed")

                if log.isEnabledFor(logging.DEBUG):
                    log.debug("W: %s", " ".join(f"{b:02x}" for b in safe_payload))
                self._trace_frame("TX", safe_payload)
            except OSError as e:
                log.error("Write error mode=%s payload=%s err=%s", self._transport_mode, safe_payload, e)

    def _read(self) -> Optional[bytes]:
        """
        Read an 8-byte interrupt report. Returns None on timeout/no data.
        """
        if not self._dev:
            return None
        try:
            with self._io_lock:
                if not self._dev:
                    return None
                # Use explicit zero-timeout read so hidapi never blocks the
                # I/O lock (some builds ignore set_nonblocking on read()).
                try:
                    data = self._dev.read(8, 0)
                except TypeError:
                    data = self._dev.read(8)
            if data:
                data = bytes(data)
                self._msg_count += 1
                self._read_error_streak = 0
                if log.isEnabledFor(logging.DEBUG):
                    log.debug("R[%d]: %s", self._msg_count, " ".join(f"{b:02x}" for b in data))
                self._trace_frame("RX", data)
                return data
        except OSError as e:
            self._read_error_streak += 1
            if self._read_error_streak in {1, 3, 8} or self._read_error_streak % 20 == 0:
                log.error("Read error (streak=%d): %s", self._read_error_streak, e)
            if self._read_error_streak >= 8:
                self._recover_after_read_errors()
        return None

    def _recover_after_read_errors(self):
        now = time.monotonic()
        if now - self._last_recover_attempt < 3.0:
            return
        self._last_recover_attempt = now

        log.warning("Attempting HID recovery after read error streak=%d", self._read_error_streak)
        with self._io_lock:
            if self._dev:
                try:
                    self._dev.close()
                except OSError:
                    pass
                self._dev = None

        time.sleep(0.2)
        if self.open():
            self.send_init(self._current_status)
            self._read_error_streak = 0
            log.info("HID recovery successful")
        else:
            log.error("HID recovery failed")

    # ── Event System ────────────────────────────────────────────

    def on(self, event: str, callback: Callable):
        """Register an event callback. Multiple callbacks per event are supported."""
        self._callbacks.setdefault(event, []).append(callback)
        log.debug("on(%s): callbacks=%d", event, len(self._callbacks[event]))

    def _emit(self, event: str, *args):
        """Fire all callbacks for an event."""
        log.debug("EMIT %s args=%s", event, args)
        for cb in self._callbacks.get(event, []):
            try:
                cb(*args)
            except Exception:
                log.exception("Callback error for event %s", event)

    # ── High-level Commands ─────────────────────────────────────

    def set_time_override(self, hour: int, minute: int) -> None:
        """Override the time sent to the handset (instead of system clock)."""
        self._time_override = (int(hour) % 24, int(minute) % 60)

    def clear_time_override(self) -> None:
        """Revert to using the system clock for handset time sync."""
        self._time_override = None

    def send_init(self, status: int = Status.ONLINE):
        """
        Send the initialization / time sync message.
        This is sent periodically (every ~8 cycles) to keep the handset alive.
        Uses _time_override if set, otherwise system clock.
        """
        if self._time_override:
            hh, mm = self._time_override
        else:
            now = time.localtime()
            hh, mm = now.tm_hour, now.tm_min
        self._current_status = status
        log.debug("send_init status=%s time=%02d:%02d", int(status), hh, mm)
        self._write([0xc1, 0x33, 0x00, 0x43, 0x07, 0x9a, 0x4f])
        self._write([0x05, hh, mm, 0x06, int(status), 0x02, 0x00])

    def send_time_sync(self):
        """Resend time + current status to handset."""
        self.send_init(self._current_status)

    def ring(self):
        """Start ringing the handset for an incoming call."""
        self._write([0x84, 0x23, 0x00, 0x01, 0x80, 0x00, 0x00])

    def display_caller_id(self, caller_name: str):
        """
        Display caller ID on handset during incoming call.
        Caller name is truncated/padded to 21 chars.
        """
        name = _pad(_sanitize_latin1(caller_name), 21, '\x00')
        name_bytes = _chars_to_bytes(name)
        now = time.localtime()
        self._write([0x82, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00])
        self._write([0xc5, 0x33, 0xff, 0x43, 0x1f, 0x9a, 0x00])
        self._write([0x44, 0x03, 0x04, now.tm_mon, now.tm_mday, now.tm_hour, now.tm_min])
        self._write([0x43, 0x0b, name_bytes[0], name_bytes[1], name_bytes[2], name_bytes[3], name_bytes[4]])
        self._write([0x42, name_bytes[5], name_bytes[6], name_bytes[7], name_bytes[8], name_bytes[9], name_bytes[10]])
        self._write([0x41, name_bytes[11], name_bytes[12], name_bytes[13], name_bytes[14], name_bytes[15], name_bytes[16]])
        self._write([0x05, name_bytes[17], name_bytes[18], name_bytes[19], name_bytes[20], name_bytes[21], 0x00])

    def setup_call_from_handset(self):
        """Send the call initiation sequence (handset pressed call button)."""
        self._timeline("q9 setup_call_from_handset")
        self._write([0x82, 0x22, 0x11, 0x00, 0x00, 0x00, 0x00])
        self._write([0x85, 0x33, 0x11, 0x68, 0x01, 0x01, 0x00])
        self._write([0x83, 0x33, 0x11, 0x67, 0x00, 0x00, 0x00])
        self._write([0x82, 0x43, 0x11, 0x00, 0x00, 0x00, 0x00])

    def start_local_audio_call(self):
        """Run handset-originated call setup (q9 -> q10 only).

        Matches cit200xSkype flow:
        - q9: setup_call_from_handset()
        - q10: confirm_call_initiated()

        q17 (confirm_call_connected) is sent later when the platform reports
        call answered, or when handset emits 0x82 0x44 0x11.
        """

        def _seq():
            with self._call_setup_lock:
                if self._call_setup_active:
                    log.debug("call_setup overlap: skip")
                    self._trace_frame("EV", "call_setup skipped overlap")
                    return
                self._call_setup_active = True
                log.debug("call_setup begin delay_a=%.3f", self._call_setup_delay)

            try:
                self.setup_call_from_handset()
                time.sleep(self._call_setup_delay)
                self.confirm_call_initiated()
                # Handset local dial tone is generated by device firmware and can
                # persist until a dial-action keypath occurs. Sending dial-confirm
                # frame here mimics that transition for backend-driven calls.
                time.sleep(0.05)
                self._timeline("q19 dial_confirm_nudge")
                self.confirm_dial()
            finally:
                with self._call_setup_lock:
                    self._call_setup_active = False
                log.debug("call_setup end")

        threading.Thread(target=_seq, daemon=True).start()

    def confirm_call_initiated(self):
        """Confirm to handset that call is being placed."""
        self._timeline("q10 confirm_call_initiated")
        self._write([0xc1, 0x33, 0xff, 0x43, 0x04, 0x9a, 0x51])
        self._write([0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00])

    def confirm_call_connected(self):
        """Confirm to handset that outgoing call was accepted."""
        self._timeline("q17 confirm_call_connected")
        self._write([0x83, 0x32, 0xff, 0x43, 0x00, 0x00, 0x00])

    def confirm_outgoing_answered(self):
        """Semantic alias: remote answered outgoing call (q17)."""
        self.confirm_call_connected()

    def force_call_audio_connected(self):
        """Force handset into connected-audio call state (q17)."""
        self.confirm_call_connected()

    def answer_incoming_call(self):
        """Send answer-call sequence when handset picks up incoming call."""
        self._write([0x85, 0x33, 0x11, 0x68, 0x01, 0x01, 0x00])
        self._write([0x82, 0x43, 0x11, 0x00, 0x00, 0x00, 0x00])

    def end_call_from_remote(self):
        """Notify handset that the remote side (or PC) ended the call. Plays busy tone."""
        self._write([0x84, 0x53, 0x11, 0x01, 0x00, 0x00, 0x00])

    def end_call_from_handset(self):
        """Send end-call sequence when handset hung up."""
        self._write([0x82, 0x52, 0x11, 0x00, 0x00, 0x00, 0x00])

    def reject_incoming_call(self):
        """Send rejection sequence when handset rejects incoming call."""
        self._write([0x83, 0x32, 0x11, 0x43, 0x00, 0x00, 0x00])
        self._write([0x84, 0x53, 0x00, 0x01, 0x00, 0x00, 0x00])

    def confirm_hold(self):
        """Confirm hold/resume toggle."""
        self._write([0x83, 0x32, 0x11, 0x35, 0x00, 0x00, 0x00])

    def confirm_dial(self):
        """Confirm that we are initiating the dialed call."""
        self._write([0x83, 0x32, 0x11, 0x35, 0x00, 0x00, 0x00])

    def send_contacts(self, contacts: list[Contact], total_count: Optional[int] = None):
        """
        Send contact list to the handset (for the contacts menu).
        Uses 0xCN multi-message framing with countdown sub-headers.
        """
        max_wire_contacts = 33
        wire_contacts = contacts[:max_wire_contacts]
        if len(contacts) > max_wire_contacts:
            log.warning("Truncating contacts payload: %d -> %d", len(contacts), max_wire_contacts)

        frame_delay = self._contacts_frame_delay_s
        record_delay = self._contacts_contact_delay_s
        restore_mode = None
        effective_mode = self._contacts_transport_mode or self._transport_mode
        if self._transport_mode == "dual" and effective_mode == "dual":
            effective_mode = "feature_only"
            log.debug("contacts tx: dual mode auto-fallback to feature_only")
        if self._transport_mode == "dual" and self._contacts_transport_mode in {"feature_only", "output_only"}:
            restore_mode = self._transport_mode
            self._transport_mode = self._contacts_transport_mode
            log.debug("contacts tx temporary transport_mode=%s", self._transport_mode)
        elif self._transport_mode == "dual" and effective_mode in {"feature_only", "output_only"}:
            restore_mode = self._transport_mode
            self._transport_mode = effective_mode
            log.debug("contacts tx adaptive transport_mode=%s", self._transport_mode)

        def _write_contact_frame(frame: list[int]):
            t0 = time.perf_counter()
            self._write(frame)
            dt_ms = (time.perf_counter() - t0) * 1000.0
            if dt_ms > 150.0:
                log.warning("contacts frame write slow: %.1fms frame=%s", dt_ms, " ".join(f"{b:02x}" for b in frame))
            if frame_delay > 0.0:
                time.sleep(frame_delay)

        try:
            burst_t0 = time.perf_counter()
            self._contacts = wire_contacts
            _write_contact_frame([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])

            if not wire_contacts:
                _write_contact_frame([0xc1, 0x33, 0x01, 0x43, 0x06, 0x9a, 0x4c])
                _write_contact_frame([0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00])
                return

            if total_count is None:
                total = len(wire_contacts)
            else:
                total = _clamp_byte(total_count, len(wire_contacts))
            if total < len(wire_contacts):
                total = len(wire_contacts)
            for i, contact in enumerate(wire_contacts):
                cname = _pad(_sanitize_latin1(contact.name or contact.handle), 13)
                chandle = _pad(_sanitize_latin1(contact.handle or contact.name), 16)
                cname_bytes = _chars_to_bytes(cname)
                chandle_bytes = _chars_to_bytes(chandle)
                cstat = _clamp_byte(contact.status, int(Status.OFFLINE))
                cindex = _clamp_byte(contact.index, i)
                if cindex >= total:
                    cindex = i

                log.debug(
                    "contacts frame idx=%d total=%d status=%d name=%r handle=%r",
                    cindex,
                    total,
                    cstat,
                    contact.name,
                    contact.handle,
                )

                # c6 = 6 messages following this header
                _write_contact_frame([0xc6, 0x33, 0x01, 0x43, 0x23, 0x9a, 0x4c])
                _write_contact_frame([0x45, 0x00, cindex, 0x00, total, cname_bytes[0], cname_bytes[1]])
                _write_contact_frame([0x44, cname_bytes[2], cname_bytes[3], cname_bytes[4], cname_bytes[5], cname_bytes[6], cname_bytes[7]])
                _write_contact_frame([0x43, cname_bytes[8], cname_bytes[9], cname_bytes[10], cname_bytes[11], cname_bytes[12], cname_bytes[13]])
                _write_contact_frame([0x42, chandle_bytes[0], chandle_bytes[1], chandle_bytes[2], chandle_bytes[3], chandle_bytes[4], chandle_bytes[5]])
                _write_contact_frame([0x41, chandle_bytes[6], chandle_bytes[7], chandle_bytes[8], chandle_bytes[9], chandle_bytes[10], chandle_bytes[11]])
                _write_contact_frame([0x03, chandle_bytes[12], chandle_bytes[13], cstat, 0x00, 0x00, 0x00])
                if record_delay > 0.0:
                    time.sleep(record_delay)
            burst_ms = (time.perf_counter() - burst_t0) * 1000.0
            log.info("contacts tx complete: sent=%d total=%d mode=%s duration=%.1fms", len(wire_contacts), total, self._transport_mode, burst_ms)
        finally:
            if restore_mode:
                self._transport_mode = restore_mode

    def send_contacts_legacy(
        self,
        ordered_contacts: list[Contact],
        request_index: int,
        transport_override: Optional[str] = None,
        first_only: bool = False,
    ):
        """Legacy qwerty==2 contacts responder (cit200xSkype-compatible)."""
        frame_delay = self._contacts_frame_delay_s
        record_delay = self._contacts_contact_delay_s
        restore_mode = None

        effective_mode = self._contacts_transport_mode or self._transport_mode
        if self._transport_mode == "dual" and effective_mode == "dual":
            effective_mode = "feature_only"
            log.debug("contacts tx: dual mode auto-fallback to feature_only")
        chosen_mode = (transport_override or self._contacts_transport_mode or "").strip().lower()
        if chosen_mode not in {"", "feature_only", "output_only", "dual"}:
            chosen_mode = ""

        if self._transport_mode == "dual" and chosen_mode in {"feature_only", "output_only"}:
            restore_mode = self._transport_mode
            self._transport_mode = chosen_mode
            log.debug("contacts tx temporary transport_mode=%s", self._transport_mode)
        elif self._transport_mode == "dual" and effective_mode in {"feature_only", "output_only"}:
            restore_mode = self._transport_mode
            self._transport_mode = effective_mode
            log.debug("contacts tx adaptive transport_mode=%s", self._transport_mode)
        elif self._transport_mode in {"feature_only", "output_only"} and chosen_mode in {"feature_only", "output_only"} and chosen_mode != self._transport_mode:
            restore_mode = self._transport_mode
            self._transport_mode = chosen_mode
            log.debug("contacts tx override transport_mode=%s", self._transport_mode)

        def _write_contact_frame(frame: list[int]):
            self._write(frame)
            if frame_delay > 0.0:
                time.sleep(frame_delay)

        def _format_legacy(text: str, length: int, suffix: str = "\x20") -> str:
            safe = _sanitize_latin1(text)
            if len(safe) > length:
                chars = list(safe)
                chars[len(safe) - 1] = suffix
                safe = "".join(chars)
            while len(safe) <= length:
                safe += suffix
            return safe

        try:
            _write_contact_frame([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])

            legacy_contacts = ordered_contacts[:33]
            total = len(legacy_contacts)
            idx = max(0, int(request_index))
            if total <= 0 or idx >= total:
                _write_contact_frame([0xc1, 0x33, 0x01, 0x43, 0x06, 0x9a, 0x4c])
                _write_contact_frame([0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00])
                return

            send_indices = [idx]
            if not first_only and idx == 0 and total > 1:
                send_indices.append(1)

            for curr_index in send_indices:
                c = legacy_contacts[curr_index]
                has_name = bool(str(c.name or "").strip())
                if has_name:
                    cname = _format_legacy(c.name, 13)
                    chandle = _format_legacy(c.handle, 16)
                else:
                    chandle = _format_legacy(c.handle, 13)
                    cname = chandle

                cstat = _clamp_byte(c.status, int(Status.OFFLINE))
                cname_bytes = _chars_to_bytes(cname)
                chandle_bytes = _chars_to_bytes(chandle)

                log.debug(
                    "contacts legacy frame idx=%d total=%d status=%d name=%r handle=%r",
                    curr_index,
                    total,
                    cstat,
                    c.name,
                    c.handle,
                )

                _write_contact_frame([0xc6, 0x33, 0x01, 0x43, 0x23, 0x9a, 0x4c])
                _write_contact_frame([0x45, 0x00, _clamp_byte(curr_index), 0x00, _clamp_byte(total), cname_bytes[0], cname_bytes[1]])
                _write_contact_frame([0x44, cname_bytes[2], cname_bytes[3], cname_bytes[4], cname_bytes[5], cname_bytes[6], cname_bytes[7]])
                _write_contact_frame([0x43, cname_bytes[8], cname_bytes[9], cname_bytes[10], cname_bytes[11], cname_bytes[12], cname_bytes[13]])
                _write_contact_frame([0x42, chandle_bytes[0], chandle_bytes[1], chandle_bytes[2], chandle_bytes[3], chandle_bytes[4], chandle_bytes[5]])
                _write_contact_frame([0x41, chandle_bytes[6], chandle_bytes[7], chandle_bytes[8], chandle_bytes[9], chandle_bytes[10], chandle_bytes[11]])
                _write_contact_frame([0x03, chandle_bytes[12], chandle_bytes[13], cstat, 0x00, 0x00, 0x00])
                if record_delay > 0.0:
                    time.sleep(record_delay)

            log.info("contacts legacy tx complete: sent=%d total=%d mode=%s req=%d", len(send_indices), total, self._transport_mode, idx)
        finally:
            if restore_mode:
                self._transport_mode = restore_mode

    def send_contact_details(
        self,
        contact: Contact,
        handle_full: str = "",
        language: str = "",
        birthday_ymd: str = "",
        gender: int = 0xFF,
    ):
        """
        Send full contact details to handset (detail view).
        Uses c9 framing (9 following messages).
        """
        self._write([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])
        chandle = _pad(_sanitize_latin1(handle_full or contact.handle), 26, '\x00')
        chandle_bytes = _chars_to_bytes(chandle)
        clang = _pad(_sanitize_latin1(language), 9, '\x00')
        lang_bytes = _chars_to_bytes(clang)
        bday = _birthday_bytes(birthday_ymd)

        self._write([0xc9, 0x33, 0x01, 0x43, 0x35, 0x9a, 0x4d])
        self._write([0x48, 0x00, 0x00, 0x00, chandle_bytes[0], chandle_bytes[1], chandle_bytes[2]])
        self._write([0x47, chandle_bytes[3], chandle_bytes[4], chandle_bytes[5], chandle_bytes[6], chandle_bytes[7], chandle_bytes[8]])
        self._write([0x46, chandle_bytes[9], chandle_bytes[10], chandle_bytes[11], chandle_bytes[12], chandle_bytes[13], chandle_bytes[14]])
        self._write([0x45, chandle_bytes[15], chandle_bytes[16], chandle_bytes[17], chandle_bytes[18], chandle_bytes[19], chandle_bytes[20]])
        self._write([0x44, chandle_bytes[21], chandle_bytes[22], chandle_bytes[23], chandle_bytes[24], chandle_bytes[25], chandle_bytes[26]])
        self._write([0x43, 0x00, 0x00, 0x00, 0x00, 0x00, lang_bytes[0]])
        self._write([0x42, lang_bytes[1], lang_bytes[2], lang_bytes[3], lang_bytes[4], lang_bytes[5], lang_bytes[6]])
        self._write([0x41, lang_bytes[7], lang_bytes[8], lang_bytes[9], bday[0], bday[1], bday[2]])
        self._write([0x03, bday[3], _clamp_byte(gender, 0xFF), _clamp_byte(contact.status), 0x00, 0x00, 0x00])

    def send_contact_numbers_page(self, office: str = "", home: str = "", mobile: str = ""):
        """Send contact detail page 1 (office/home/mobile packed digits)."""
        office_b = _pack_tel_digits(office, 10)
        home_b = _pack_tel_digits(home, 10)
        mobile_b = _pack_tel_digits(mobile, 10)

        self._write([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])
        self._write([0xc6, 0x33, 0x01, 0x43, 0x23, 0x9a, 0x4d])
        self._write([0x45, 0x00, 0x01, 0x01, office_b[0], office_b[1], office_b[2]])
        self._write([0x44, office_b[3], office_b[4], office_b[5], office_b[6], office_b[7], office_b[8]])
        self._write([0x43, office_b[9], home_b[0], home_b[1], home_b[2], home_b[3], home_b[4]])
        self._write([0x42, home_b[5], home_b[6], home_b[7], home_b[8], home_b[9], mobile_b[0]])
        self._write([0x41, mobile_b[1], mobile_b[2], mobile_b[3], mobile_b[4], mobile_b[5], mobile_b[6]])
        self._write([0x03, mobile_b[7], mobile_b[8], mobile_b[9], 0x00, 0x00, 0x00])

    def send_contact_bio_page(self, bio_text: str = "", local_hh: Optional[int] = None, local_mm: Optional[int] = None):
        """Send contact detail page 2+ (address/time style, used for bio text)."""
        addr = _pad(_sanitize_latin1(bio_text), 38, '\x00')
        addr_b = _chars_to_bytes(addr)
        now = time.localtime()
        hh = _clamp_byte(now.tm_hour if local_hh is None else local_hh)
        mm = _clamp_byte(now.tm_min if local_mm is None else local_mm)

        self._write([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])
        self._write([0xc8, 0x33, 0x01, 0x43, 0x2f, 0x9a, 0x4d])
        self._write([0x47, 0x00, 0x01, 0x02, addr_b[0], addr_b[1], addr_b[2]])
        self._write([0x46, addr_b[3], addr_b[4], addr_b[5], addr_b[6], addr_b[7], addr_b[8]])
        self._write([0x45, addr_b[9], addr_b[10], addr_b[11], addr_b[12], addr_b[13], addr_b[14]])
        self._write([0x44, addr_b[15], addr_b[16], addr_b[17], addr_b[18], addr_b[19], addr_b[20]])
        self._write([0x43, addr_b[21], addr_b[22], addr_b[23], addr_b[24], addr_b[25], addr_b[26]])
        self._write([0x42, addr_b[27], addr_b[28], addr_b[29], addr_b[30], addr_b[31], addr_b[32]])
        self._write([0x41, addr_b[33], addr_b[34], addr_b[35], addr_b[36], addr_b[37], addr_b[38]])
        self._write([0x03, 0x00, hh, mm, 0x00, 0x00, 0x00])

    def send_status_echo(self, status: int):
        """Echo current status back when status list is viewed."""
        self._write([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])
        self._write([0xc1, 0x33, 0x01, 0x43, 0x03, 0x9a, 0x42])
        self._write([0x01, int(status), 0x00, 0x00, 0x00, 0x00, 0x00])

    def confirm_status_change(self, status: int):
        """Confirm a status change to the handset."""
        self._current_status = status
        self._write([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])
        self._write([0xc1, 0x33, 0x01, 0x43, int(status), 0x9a, 0x43])
        self._write([0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00])

    def send_voicemail_count(self, count: int = 0):
        """Send voicemail count to handset."""
        self._write([0x83, 0x32, 0x01, 0x43, 0x00, 0x00, 0x00])
        self._write([0xc1, 0x33, 0x01, 0x43, 0x06, 0x9a, 0x48])
        self._write([0x04, 0x00, 0x00, 0x00, count, 0x00, 0x00])

    # ── Event Processing (main loop) ───────────────────────────

    def poll(self):
        """
        Read one message from the device and process it.
        Call this repeatedly from your event loop.
        Returns True if data was processed, False if no data.
        """
        data = self._read()
        if not data or len(data) < 8:
            return False
        log.debug("poll: processing frame len=%d", len(data))
        self._process_message(data)
        return True

    def _process_message(self, data: bytes):
        """
        Decode an 8-byte handset message and update internal state.
        Mirrors the qwerty state machine from cit200xSkype.py.
        """
        d = data  # shorthand
        log.debug("process state=%d frame=%s", self._state, data.hex())

        # End call from handset
        if d[1] == 0x84 and d[2] == 0x51 and d[3] == 0x11 and d[4] == 0x01:
            log.info("Handset: end call")
            self._timeline("rx end_call 84 51 11 01")
            self._set_state(0, "end_call")
            self.end_call_from_handset()
            self._emit(Event.END_CALL)
            return

        # Ping (keep-alive from handset)
        if (d[1] == 0x83 and d[2] == 0x34 and d[4] == 0x43 and d[5] == 0x00) or \
           (d[1] == 0xc1 and d[2] == 0x31 and d[3] == 0xff and d[4] == 0x43 and d[5] == 0x04 and d[6] == 0x9a and d[7] == 0x50):
            log.debug("Handset: ping")
            self._emit(Event.PING)
            return

        # State-dependent processing
        if self._state == 6:
            # Contacts menu opened — data[3] = contact index
            log.info("Handset: contacts menu (index %d)", d[3])
            self._emit(Event.CONTACTS_REQUEST, d[3])
            self._set_state(0, "contacts_done")
            return

        if self._state == 8:
            # Contact details opened
            contact_idx = d[3]
            more_index = d[4]
            log.info("Handset: contact details (index %d, more %d)", contact_idx, more_index)
            if more_index == 0x00:
                self._emit(Event.CONTACT_DETAILS, contact_idx, "details")
            elif more_index > 0x00:
                self._emit(Event.CONTACT_DETAILS, contact_idx, more_index)
            self._set_state(0, "details_done")
            return

        if self._state == 5:
            # Status change selected — data[2] = new status index
            new_status = d[2]
            log.info("Handset: status change to %d", new_status)
            self.confirm_status_change(new_status)
            self._emit(Event.STATUS_CHANGE, new_status)
            self._set_state(0, "status_change_done")
            return

        if self._state == 18:
            # Accumulating callee data (multi-message dial sequence)
            if d[1] > 0x06 and d[1] < 0x46:
                # More callee data coming (countdown sub-header)
                self._callee_buf.extend(d[2:8])
            elif d[1] > 0x00 and d[1] < 0x07:
                # Final callee chunk
                remaining = d[1]
                self._callee_buf.extend(d[2:2 + remaining])
                callee = self._extract_callee()
                log.info("Handset: dial request")
                self.confirm_dial()
                self._emit(Event.DIAL, callee)
                self._set_state(0, "dial_done")
            else:
                log.warning("Unexpected callee data: %s", data.hex())
                self._set_state(0, "dial_unexpected")
            return

        # ── Stateless event matching ────────────────────────────

        # Contacts/Skype button
        if d[1] == 0xc1 and d[2] == 0x31 and d[3] == 0x01 and d[4] == 0x43 and d[5] == 0x05 and d[6] == 0x9a and d[7] == 0x4c:
            log.info("Handset: contacts button")
            self._set_state(6, "contacts_button")  # Next read will have the contact index
            nxt = self._read()
            if nxt and len(nxt) >= 8:
                self._process_message(bytes(nxt))
            return

        # Status menu
        if d[1] == 0x86 and d[2] == 0x31 and d[3] == 0x01 and d[4] == 0x43 and d[5] == 0x02 and d[6] == 0x9a and d[7] == 0x42:
            log.info("Handset: status menu")
            self.send_status_echo(self._current_status)
            self._emit(Event.STATUS_MENU)
            self._set_state(0, "status_menu")
            return

        # Contact details request
        if d[1] == 0xc1 and d[2] == 0x31 and d[3] == 0x01 and d[4] == 0x43 and d[5] == 0x05 and d[6] == 0x9a and d[7] == 0x4d:
            log.info("Handset: details request")
            self._set_state(8, "details_request")
            nxt = self._read()
            if nxt and len(nxt) >= 8:
                self._process_message(bytes(nxt))
            return

        # Status change request
        if d[1] == 0xc1 and d[2] == 0x31 and d[3] == 0x01 and d[4] == 0x43 and d[5] == 0x03 and d[6] == 0x9a and d[7] == 0x43:
            log.info("Handset: status change request")
            self._set_state(5, "status_change_request")
            nxt = self._read()
            if nxt and len(nxt) >= 8:
                self._process_message(bytes(nxt))
            return

        # Call button (green button)
        if d[1] == 0xc1 and d[2] == 0x21 and d[3] == 0x11 and d[4] == 0x04 and d[5] == 0x80 and d[6] == 0x9a and d[7] == 0x60:
            log.info("Handset: call button")
            self._timeline("rx call_button c1 21 11 04 80 9a 60")
            self.arm_trace_window(reason="call_button")
            self.start_local_audio_call()
            self._emit(Event.CALL_BUTTON)
            self._set_state(0, "call_button")
            return

        # Dial sequence start (callee data begins)
        if d[1] in (0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6) and d[2] == 0x31 and d[3] == 0x11 and d[4] == 0x35:
            self._callee_buf = bytearray(d[6:8])
            self._set_state(18, "dial_sequence_start")
            return

        # Voicemail view
        if d[1] == 0xc1 and d[2] == 0x31 and d[3] == 0x01 and d[4] == 0x43 and d[5] == 0x05 and d[6] == 0x9a and d[7] == 0x48:
            log.info("Handset: voicemail view")
            self.send_voicemail_count(0)
            self._emit(Event.VOICEMAIL_VIEW)
            self._set_state(0, "voicemail_view")
            return

        # Voicemail delete
        if d[1] == 0xc2 and d[2] == 0x31 and d[3] == 0x01 and d[4] == 0x43 and d[5] == 0x09 and d[6] == 0x9a and d[7] == 0x49:
            log.info("Handset: voicemail delete")
            self._emit(Event.VOICEMAIL_DELETE)
            self._set_state(0, "voicemail_delete")
            return

        # Reject incoming call
        if d[1] == 0x86 and d[2] == 0x31 and d[3] == 0x11 and d[4] == 0x43 and d[5] == 0x02 and d[6] == 0x9a:
            log.info("Handset: reject incoming call")
            self._timeline("rx reject_incoming 86 31 11 43 02 9a")
            self.reject_incoming_call()
            self._emit(Event.REJECT_INCOMING)
            self._set_state(0, "reject_incoming")
            return

        # Call ready — phone finished setup, waiting for "connected" signal.
        # Respond with confirm_call_connected() to kill dial tone and open audio.
        if d[1] == 0x82 and d[2] == 0x44 and d[3] == 0x11:
            log.info("Handset: call ready, confirming connected")
            self._timeline("rx call_ready 82 44 11")
            self.confirm_call_connected()
            self._emit(Event.CALL_ACCEPTED_REMOTE)
            self._set_state(0, "call_ready")
            return

        # Incoming call — handset off-hook step 1
        if d[1] == 0x82 and d[2] == 0x11 and d[3] == 0x00:
            log.debug("Handset: incoming call accept step 1")
            # Wait for step 2
            self._set_state(0, "incoming_accept_step1")
            return

        # Incoming call — handset answered (step 2)
        if d[1] == 0x82 and d[2] == 0x24 and d[3] == 0x11:
            log.info("Handset: answered incoming call")
            self._timeline("rx answer_incoming 82 24 11")
            self.answer_incoming_call()
            self._emit(Event.ANSWER_INCOMING)
            self._set_state(0, "answer_incoming")
            return

        # Hold/Resume (R button)
        if d[1] == 0x85 and d[2] == 0x31 and d[3] == 0x11 and d[4] == 0x35 and d[5] == 0x01 and d[6] == 0x15:
            log.info("Handset: hold/resume")
            self.confirm_hold()
            self._emit(Event.HOLD_RESUME)
            self._set_state(0, "hold_resume")
            return

        # Follow-up reads for multi-byte messages (0xc1 prefix)
        if d[1] == 0xc1:
            log.debug("continuation-read trigger for 0xc1 prefix")
            self._read()  # Consume continuation
            return

        log.debug("unhandled frame in state=%d: %s", self._state, data.hex())

    def _extract_callee(self) -> str:
        """Extract the callee handle string from accumulated buffer bytes."""
        result = []
        for b in self._callee_buf:
            if 0x20 <= b < 0x7f:
                result.append(chr(b))
        return "".join(result).strip()

    # ── Standalone Test ─────────────────────────────────────────

    def run_loop(self, status: int = Status.ONLINE):
        """
        Blocking event loop for standalone testing.
        Sends periodic time sync and polls for events.
        """
        if not self.is_open:
            if not self.open():
                return

        self._running = True
        cycle = 1
        log.info("CIT200 event loop started (Ctrl+C to stop)")

        try:
            while self._running:
                self.poll()

                if cycle == 1:
                    self.send_init(status)

                if cycle >= 8:
                    cycle = 1
                else:
                    cycle += 1

                time.sleep(0.2)
        except KeyboardInterrupt:
            log.info("Interrupted")
        finally:
            self.close()


# ── Utility Functions ───────────────────────────────────────────

def _pad(text: str, length: int, fill: str = '\x20') -> str:
    """Pad or truncate text to exactly length+1 characters."""
    if text is None:
        text = ""
    text = text[:length + 1]
    while len(text) <= length:
        text += fill
    return text


def _clamp_byte(value, default: int = 0) -> int:
    """Coerce any value to one unsigned byte (0..255)."""
    try:
        iv = int(value)
    except (TypeError, ValueError):
        iv = int(default)
    return max(0, min(255, iv))


def _sanitize_latin1(text: Optional[str]) -> str:
    """Normalize arbitrary text to display-safe latin-1 bytes."""
    if text is None:
        return ""
    raw = str(text).replace("\x00", " ")
    safe = raw.encode("latin-1", errors="replace").decode("latin-1")
    return "".join(ch if 0x20 <= ord(ch) <= 0xFF else " " for ch in safe)


def _chars_to_bytes(text: str) -> list[int]:
    """Convert a latin-1-safe string to byte values."""
    return [ord(ch) for ch in text]


def _pack_tel_digits(value: str, out_bytes: int = 10) -> list[int]:
    """Pack decimal digits as handset nibble pairs, A-filling odd tails."""
    digits = "".join(ch for ch in (value or "") if ch.isdigit())
    packed: list[int] = []
    i = 0
    while i < len(digits):
        a = digits[i]
        b = digits[i + 1] if i + 1 < len(digits) else "A"
        try:
            packed.append(int(a + b, 16))
        except Exception:
            packed.append(0xAA)
        i += 2
    while len(packed) < out_bytes:
        packed.append(0xAA)
    return packed[:out_bytes]


def _birthday_bytes(ymd: str) -> list[int]:
    """Encode YYYY-MM-DD into 4 bytes used by handset details page."""
    try:
        y, m, d = str(ymd or "").strip().split("-")
        if len(y) != 4:
            raise ValueError("invalid year")
        return [int(y[0:2], 16), int(y[2:4], 16), int(m, 16), int(d, 16)]
    except Exception:
        return [0xFF, 0x00, 0x00, 0x00]


# ── Standalone Entry Point ──────────────────────────────────────

if __name__ == "__main__":
    import sys

    logging.basicConfig(
        level=logging.DEBUG if "--debug" in sys.argv else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    phone = CIT200Device()

    # Register some test callbacks
    phone.on(Event.CALL_BUTTON, lambda: print(">>> CALL BUTTON PRESSED"))
    phone.on(Event.END_CALL, lambda: print(">>> CALL ENDED"))
    phone.on(Event.CONTACTS_REQUEST, lambda idx: print(f">>> CONTACTS REQUEST (index {idx})"))
    phone.on(Event.CONTACT_DETAILS, lambda idx, what: print(f">>> CONTACT DETAILS (index {idx}, {what})"))
    phone.on(Event.STATUS_CHANGE, lambda s: print(f">>> STATUS CHANGED TO {Status(s).name}"))
    phone.on(Event.DIAL, lambda callee: print(f">>> DIALING: {callee}"))
    phone.on(Event.ANSWER_INCOMING, lambda: print(">>> ANSWERED INCOMING CALL"))
    phone.on(Event.REJECT_INCOMING, lambda: print(">>> REJECTED INCOMING CALL"))
    phone.on(Event.HOLD_RESUME, lambda: print(">>> HOLD/RESUME"))
    phone.on(Event.PING, lambda: None)  # Suppress ping spam

    # Provide test contacts when requested
    def on_contacts(idx):
        phone.send_contacts([
            Contact(index=0, handle="testuser1", name="Test User 1", status=Status.ONLINE),
            Contact(index=1, handle="testuser2", name="Test User 2", status=Status.AWAY),
        ])
    phone.on(Event.CONTACTS_REQUEST, on_contacts)

    print("Starting CIT200 standalone test...")
    print("Press keys on the handset to see events.")
    print("Ctrl+C to exit.\n")
    phone.run_loop()
